{
    'name': 'Lush Nails - Appointments',
    'version': '0.1.0',
    'summary': 'Gestión de citas para Lush Nails',
    'description': 'Módulo para gestionar clientes, servicios, empleados, sucursales y citas.',
    'author': 'You',
    'maintainers': ['snxz'],
    'license': 'LGPL-3',
    'category': 'Services/Appointment',
    'depends': ['base', 'mail', 'portal', 'calendar'],
    'data': [
        'security/lush_nails_security.xml',
        'security/ir.model.access.csv',
        'data/groups.xml',
        'views/service_views.xml',
        'views/employee_views.xml',
        'views/branch_views.xml',
        'views/appointment_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
